apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv
  namespace: efklog
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: aws-ebs  # Replace with your storage class name
  awsElasticBlockStore:
    volumeID: vol-0e2fb27d727086cd3
    fsType: ext4  # Adjust according to your filesystem type
