apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
  namespace: efklog
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi  # Adjust the size according to your requirements
  storageClassName: aws-ebs  # Replace with your EBS storage class name or remove this line if using default storage class
